/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package combatdemo;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author kevin.lawrence
 */
public class CombatPanel extends javax.swing.JPanel {

    /**
     * Creates new form CombatPanel
     */
    public CombatPanel() {
        initComponents();
        initData();
        displayAttacks();
    }
    
    //<editor-fold defaultstate="collapsed" desc="Methods">
    private void initData(){
        friendAttacks = new ArrayList<Attack>();
        friendAttacks.add(new Attack("Flame", 10, 30, .5));
        friendAttacks.add(new Attack("Doom", 10, 20, .75));
        friendAttacks.add(new Attack("Bring the PAIN!", 70, 80, .15));
    }
    
    private void displayAttacks(){        
        if (friendAttacks != null){
            DefaultListModel listModel = new DefaultListModel();
            
            for(Attack attack : friendAttacks){
                listModel.addElement(attack.getDisplay());
            }
            this.jlstFriendAttacks.setModel(listModel);
        }
    }
    
    private void processAttack(){
        if (!jlstFriendAttacks.getSelectedValuesList().isEmpty()){
            System.out.printf("Selected attack = #%d %s\n",jlstFriendAttacks.getSelectedIndex(), jlstFriendAttacks.getSelectedValue().toString());
            System.out.printf("Look up attack as %s\n", this.friendAttacks.get(jlstFriendAttacks.getSelectedIndex()).getDisplay());
        }  
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Properties">
    private Image friendImage;
    private String enemyName = "";
    private Image enemyImage;
    private ArrayList<Attack> friendAttacks;
    
    /**
     * @return the friendName
     */
    public String getFriendName() {
        return this.jlblFriendName.getText();
    }
    
    /**
     * @param friendName the friendName to set
     */
    public void setFriendName(String friendName) {
        this.jlblFriendName.setText(friendName);
    }
    
    /**
     * @return the friendImage
     */
    public Image getFriendImage() {
        return friendImage;
    }
    
    /**
     * @param friendImage the friendImage to set
     */
    public void setFriendImage(Image friendImage) {
        this.friendImage = friendImage;
        this.jlblFriendImage.setIcon(new ImageIcon(friendImage));
    }
    
    /**
     * @return the enemyName
     */
    public String getEnemyName() {
        return this.jlblEnemyName.getText();
    }
    
    /**
     * @param enemyName the enemyName to set
     */
    public void setEnemyName(String enemyName) {
        this.jlblEnemyName.setText(enemyName);
    }
    
    /**
     * @return the enemyImage
     */
    public Image getEnemyImage() {
        return enemyImage;
    }
    
    /**
     * @param enemyImage the enemyImage to set
     */
    public void setEnemyImage(Image enemyImage) {
        this.enemyImage = enemyImage;
        this.jlblEnemyImage.setIcon(new ImageIcon(enemyImage));
    }
    //</editor-fold>
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        jlblFriendName = new javax.swing.JLabel();
        jlblFriendImage = new javax.swing.JLabel();
        pnlBattle = new javax.swing.JPanel();
        jbtnAttack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlstFriendAttacks = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jlblEnemyName = new javax.swing.JLabel();
        jlblEnemyImage = new javax.swing.JLabel();

        pnlLeft.setBackground(new java.awt.Color(204, 255, 204));

        jlblFriendName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblFriendName.setText("<friend>");

        jlblFriendImage.setText(" ");

        pnlBattle.setBackground(new java.awt.Color(255, 204, 204));

        jbtnAttack.setText("Attack!");
        jbtnAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAttackActionPerformed(evt);
            }
        });

        jlstFriendAttacks.setBackground(new java.awt.Color(255, 204, 204));
        jlstFriendAttacks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlstFriendAttacks);

        org.jdesktop.layout.GroupLayout pnlBattleLayout = new org.jdesktop.layout.GroupLayout(pnlBattle);
        pnlBattle.setLayout(pnlBattleLayout);
        pnlBattleLayout.setHorizontalGroup(
            pnlBattleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlBattleLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlBattleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlBattleLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jbtnAttack)))
                .addContainerGap())
        );
        pnlBattleLayout.setVerticalGroup(
            pnlBattleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlBattleLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jbtnAttack)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout pnlLeftLayout = new org.jdesktop.layout.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlblFriendImage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlblFriendName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnlBattle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .add(jlblFriendName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jlblFriendImage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 297, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlBattle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jlblEnemyName.setText("<enemy>");

        jlblEnemyImage.setText(" ");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlblEnemyName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .add(jlblEnemyImage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jlblEnemyName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jlblEnemyImage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 298, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(130, 130, 130))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(pnlLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnlLeft, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAttackActionPerformed
        processAttack();
    }//GEN-LAST:event_jbtnAttackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAttack;
    private javax.swing.JLabel jlblEnemyImage;
    private javax.swing.JLabel jlblEnemyName;
    private javax.swing.JLabel jlblFriendImage;
    private javax.swing.JLabel jlblFriendName;
    private javax.swing.JList jlstFriendAttacks;
    private javax.swing.JPanel pnlBattle;
    private javax.swing.JPanel pnlLeft;
    // End of variables declaration//GEN-END:variables

}
