/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package combatdemo;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author kevin.lawrence
 */
public class CombatPanel extends javax.swing.JPanel {

    /**
     * Creates new form CombatPanel
     */
    public CombatPanel() {
        initComponents();
    }
    
    //<editor-fold defaultstate="collapsed" desc="Properties">
    private Image friendImage;
    private String enemyName = "";
    private Image enemyImage;
    
    /**
     * @return the friendName
     */
    public String getFriendName() {
        return this.jlblFriendName.getText();
    }
    
    /**
     * @param friendName the friendName to set
     */
    public void setFriendName(String friendName) {
        this.jlblFriendName.setText(friendName);
    }
    
    /**
     * @return the friendImage
     */
    public Image getFriendImage() {
        return friendImage;
    }
    
    /**
     * @param friendImage the friendImage to set
     */
    public void setFriendImage(Image friendImage) {
        this.friendImage = friendImage;
        this.jlblFriendImage.setIcon(new ImageIcon(friendImage));
    }
    
    /**
     * @return the enemyName
     */
    public String getEnemyName() {
        return this.jlblEnemyName.getText();
    }
    
    /**
     * @param enemyName the enemyName to set
     */
    public void setEnemyName(String enemyName) {
        this.jlblEnemyName.setText(enemyName);
    }
    
    /**
     * @return the enemyImage
     */
    public Image getEnemyImage() {
        return enemyImage;
    }
    
    /**
     * @param enemyImage the enemyImage to set
     */
    public void setEnemyImage(Image enemyImage) {
        this.enemyImage = enemyImage;
        this.jlblEnemyImage.setIcon(new ImageIcon(enemyImage));
    }
    //</editor-fold>
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        jlblFriendName = new javax.swing.JLabel();
        jlblFriendImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlblEnemyName = new javax.swing.JLabel();
        jlblEnemyImage = new javax.swing.JLabel();

        pnlLeft.setBackground(new java.awt.Color(204, 255, 204));

        jlblFriendName.setText("<friend>");

        jlblFriendImage.setText(" ");

        org.jdesktop.layout.GroupLayout pnlLeftLayout = new org.jdesktop.layout.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jlblFriendImage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jlblFriendName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .add(jlblFriendName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jlblFriendImage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jlblEnemyName.setText("<enemy>");

        jlblEnemyImage.setText(" ");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlblEnemyName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .add(jlblEnemyImage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jlblEnemyName)
                .add(12, 12, 12)
                .add(jlblEnemyImage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(pnlLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnlLeft, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlblEnemyImage;
    private javax.swing.JLabel jlblEnemyName;
    private javax.swing.JLabel jlblFriendImage;
    private javax.swing.JLabel jlblFriendName;
    private javax.swing.JPanel pnlLeft;
    // End of variables declaration//GEN-END:variables

}
